version: 15
jobs:
  - name: Deploy
    jobExecutor: Jarvis
    steps:
      - !CheckoutStep
        name: checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !SetBuildVersionStep
        name: set build version
        buildVersion: '@script:builtin:node:determine-project-version@'
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: build & deploy
        runInContainer: true
        image: node:16
        interpreter: !DefaultInterpreter
          commands:
            - echo "\e[1;35mSet cache folder...\e[0m"
            - yarn config set cache-folder /root/.yarn
            - echo "\e[1;32mSet cache folder successfully\e[0m"
            - echo "\e[1;35mInstall dependencies...\e[0m"
            - yarn
            - echo "\e[1;32mInstall dependencies successfully\e[0m"
            - echo "\e[1;35mStart building...\e[0m"
            - yarn build
            - echo "\e[1;32mBuild successfully\e[0m"
            - echo "\e[1;35mEstablish ssh connection...\e[0m"
            - mkdir /root/.ssh
            - chmod 700 /root/.ssh
            - cat << EOF > /root/.ssh/known_hosts
            - '@secrets:ssh_public_key@'
            - EOF
            - cat << EOF > /root/.ssh/id_rsa
            - '@secrets:ssh_private_key@'
            - EOF
            - chmod 400 /root/.ssh/id_rsa
            - echo "\e[1;32mEstablish ssh connection successfully\e[0m"
            - echo "\e[1;35mCopy project files to the remote server...\e[0m"
            - scp -r dist @secrets:ssh_user_host@:~/lcdp
            - echo "\e[1;32mCopy project files to the remote server successfully\e[0m"
            - echo "\e[1;35mDeploying...\e[0m"
            - ssh @secrets:ssh_user_host@ "
            - cd ~/lcdp
            - mv dist/favicon.ico public/favicon.ico
            - mv dist/index.html public/index.html
            - rm -rf public/static
            - mv dist/static public/static
            - rm -rf dist
            - '"'
            - echo "\e[1;32mDeployed successfully\e[0m"
        useTTY: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !BranchUpdateTrigger
        branches: master
        paths: package.json
        projects: lcdp/client
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    cpuRequirement: 250
    memoryRequirement: 256
    caches:
      - key: yarn-cache
        path: /root/.yarn
    timeout: 3600
  - name: Sync
    jobExecutor: Jarvis
    steps:
      - !CheckoutStep
        name: checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !SetBuildVersionStep
        name: set build version
        buildVersion: '@script:builtin:node:determine-project-version@'
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: sync
        runInContainer: true
        image: alpine/git:1.0.7
        interpreter: !DefaultInterpreter
          commands:
            - git config --global --unset http.extraHeader
            - git push -f @secret:codeup_lcdp_client@
        useTTY: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    jobDependencies:
      - jobName: Deploy
        requireSuccessful: true
        artifacts: '**'
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    cpuRequirement: 250
    memoryRequirement: 256
    timeout: 3600
